### ISSUE TITLE
Allow adding a struct that implements many interfaces

### ISSUE THREAD

**Issue by ghstahl** [dozm/di#3]
```go
type MyObj struct{}
type ISomething interface{
  DoSomething()
}
type ISomething2 interface{
  DoSomething2()
}
 
func (s *MyObj) DoSomething(){}
func (s *MyObj) DoSomething2(){}

```

I should be able to ask the container for MyObj, ISomething, or ISomething2.
In the fashion of asp.net core the last ISomething that was registered is returned when asking for just one.  
I should be able to ask for many,  []ISomething, or []ISomething2

All these objects can be registered as Transient, Scoped or Singleton at the same time.
Probably should just follow the asp.net core DI rules for what wins when asking for an Interface when you are in the Scoped context.

**Comment by dozm** [comment]
This library is the Golang implementation of the .NET Core DI, so the rules are basically the same.

**Comment by ghstahl** [comment]
I was looking for something like this;
```go
	
AddTransient[ISomething, ISomething2, ISomething3](b, func() interface{} { return &mySomething{} })

```
go generics probably not there yet for open ended inputs.

maybe something like the following;
```go
func Transient[T any](ctor any, implementedInterfaceTypes ...reflect.Type) *Descriptor {
	return NewConstructorDescriptor(reflectx.TypeOf[T](), Lifetime_Transient, ctor, implementedInterfaceTypes...)
}
```
where the ```[T any]``` must be a struct, and ```implementedInterfaceTypes``` are the open ended interfaces.

**Comment by dozm** [comment]
A `Descriptor` can have only one service type.
Maybe you can do it like this:
```go
v := Something{}
di.AddInstance[ISomething](b, &v)
di.AddInstance[ISomething2](b, &v)
```
or 
```go
func NewSomething() *Something {
    return &Something{}
}

di.AddTransient[ISomething](b, NewSomething)
di.AddTransient[ISomething2](b, NewSomething)
```
or
```go
di.AddSingleton[*Something](b, func() *Something { return &Something{} })
di.AddSingleton[ISomething](b, func(x *Something) ISomething { return x })
di.AddSingleton[ISomething2](b, func(x *Something) ISomething2 { return x })
```

**Comment by ghstahl** [comment]
do you have a lazy load example.
i.e.
```go
di.AddSingleton[*Something](b, func(ctn container) *Something { return &Something{

  _container: ctn
} })
```
where I can use the container later to instantiate an object.

I am assuming that I can get a hold of the container, root or scoped.
```go
di.AddScoped[*Something](b, func(ctn container) *Something { return &Something{

  _container: ctn
} })
```
Here the container would be the scoped one.

**Comment by dozm** [comment]
There are a few built-in services :
`di.Container`: renturns the container of  the current scope.
`di.ScopeFactory`: used to create a scope.

```go

type ConnHandler struct {
    scopeFactory di.ScopeFactory
}

func (h *ConnHandler) Handle(conn net.Conn) {
    // create a scope for each connection
    scope := h.scopeFactory.CreateScope()
    c := scope.Container()

    a := di.Get[A](c)
    // do something...

    // dispose the scope
    scope.Dispose()
}

func NewConnHandler(sf di.ScopeFactory) *ConnHandler {
    return &ConnHandler{scopeFactory: sf}
}

di.AddSingleton[*ConnHandler](b, NewConnHandler)
```
