### ISSUE TITLE
[QUESTION] Root container access

### ISSUE THREAD

**Issue by ghstahl** [dozm/di#6]
Should only Transient and Singleton objects be accessible from the root container?
i.e., scoped objects are hidden.

Should nothing be accessible from the root container?
i.e., force the use of the scoped factory.

```go
    scopeFactory := di.Get[di.ScopeFactory](c)
    scope := scopeFactory.CreateScope()
    c = scope.Container()
```
At the moment the root container is a scope where in the context of a web application it would be the app-scope vs a request-scope (created via middleware for each request).

Getting scoped objects from the app-scope could get me in trouble.  I would like to have some safeguards even if its configurable to stop myself from accidentally using objects I shouldn't.

**Comment by dozm** [comment]
> Should only Transient and Singleton objects be accessible from the root container?

Also need to consider the lifetime of its dependencies.


> Getting scoped objects from the app-scope could get me in trouble. I would like to have some safeguards even if its configurable to stop myself from accidentally using objects I shouldn't.

Use options:
```go
cb.ConfigureOptions(func(o *Options) {
    o.ValidateScopes = true
    o.ValidateOnBuild = true
})
```
