### ISSUE TITLE
[QUESTION] What is the difference between AddSingleton and AddInstance

### ISSUE THREAD

**Issue by ghstahl** [dozm/di#9]
In context of documentation, when would I use one over the other.

```go
    coreConfig := &CoreConfig{}	
    di.AddSingleton[*CoreConfig](builder, func() *CoreConfig{
        return coreConfig
    })
    di.AddInstance[.CoreConfig](builder, coreConfig)
```

**Comment by dozm** [comment]
Use `AddSingleton` if the CoreConfig is `di.Disposable` and you want that the container disposes the instance automatically. 
Otherwise use `AddInstance`.
